[package]
name = "sbuild"
version = "0.1.5"
authors.workspace = true
license.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
blake3 = "1.5.5"
chrono = { version = "0.4.39", default-features = false, features = ["now"] }
colored = "2.1.0"
futures = "0.3.31"
goblin = { version = "0.9.2", features = ["elf64", "elf32", "endian_fd", "std"] }
indexmap = "2.6.0"
memmap2 = "0.9.5"
reqwest = { version = "0.12.9", features = ["blocking", "http2", "rustls-tls", "stream"], default-features = false }
sbuild-linter = { version = "0.4.1", path = "../sbuild-linter" }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = { version = "1.0.133", features = ["indexmap"] }
serde_yml = "0.0.12"
squishy = { version = "0.3.2", features = ["appimage"] }
tempfile = "3.15.0"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
which = "7.0.0"
